
package javaassignment;
import java.util.Arrays;
import java.util.regex.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Kriso
 */
public class CreateUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public CreateUser() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Password Format :"
                + "\nMinimum 8 digits "
                + "\nMaximum 12 digits"
                + "\nAt Least One Uppercase"
                + "\nAt Least One Lower Case"
                + "\nAt Least One Number"
                + "\nAt least One Special Figure", "Password Format!!!!!!",JOptionPane.WARNING_MESSAGE);

   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCUName = new javax.swing.JLabel();
        LblCPass = new javax.swing.JLabel();
        LblCCPass = new javax.swing.JLabel();
        BtnCreateUser = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        LblCUID = new javax.swing.JLabel();
        TxtCUID = new javax.swing.JTextField();
        TxtCCPass = new javax.swing.JPasswordField();
        TxtCUN = new javax.swing.JTextField();
        LblValidName = new javax.swing.JLabel();
        LblValidPass = new javax.swing.JLabel();
        LblValidCPass = new javax.swing.JLabel();
        TxtCUPass = new javax.swing.JPasswordField();
        LblPT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblCUName.setText("User Name :");

        LblCPass.setText("Password :");

        LblCCPass.setText("Confirmed Password :");

        BtnCreateUser.setText("Create");
        BtnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateUserActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        LblCUID.setText("User ID :");

        TxtCCPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCCPassKeyReleased(evt);
            }
        });

        TxtCUN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCUNKeyReleased(evt);
            }
        });

        LblValidName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LblValidName.setForeground(new java.awt.Color(255, 0, 51));

        LblValidPass.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LblValidPass.setForeground(new java.awt.Color(255, 0, 51));

        LblValidCPass.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LblValidCPass.setForeground(new java.awt.Color(255, 0, 51));

        TxtCUPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCUPassActionPerformed(evt);
            }
        });
        TxtCUPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCUPassKeyReleased(evt);
            }
        });

        LblPT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblPT.setText("Create User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCCPass)
                    .addComponent(LblCUName)
                    .addComponent(LblCUID)
                    .addComponent(LblCPass))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TxtCUN)
                        .addComponent(TxtCCPass)
                        .addComponent(TxtCUID, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(TxtCUPass))
                    .addComponent(BtnCreateUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LblValidCPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(LblValidPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblValidName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(LblPT)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(LblPT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCUName)
                            .addComponent(TxtCUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblValidName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblCUID)
                    .addComponent(TxtCUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtCUPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblCPass))
                    .addComponent(LblValidPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblCCPass)
                        .addComponent(TxtCCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblValidCPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreateUser)
                    .addComponent(BtnBack))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed

        new UserPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateUserActionPerformed
        if (TxtCUN.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please insert User Name to Create an User !!","Warning!!",JOptionPane.WARNING_MESSAGE);
        return;
        
        }
        if (TxtCUID.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please insert User ID to Create an User !!","Warning!!",JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        
        if (!LblValidName.getText().trim().isEmpty())
        {
        JOptionPane.showMessageDialog(null, "Please insert correct naming format!!","Warning!!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
         if (!LblValidPass.getText().trim().isEmpty())
        {
        JOptionPane.showMessageDialog(null, "Please insert correct Password format!!","Warning!!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        {
        String Username = TxtCUN.getText();
        String Userid = TxtCUID.getText();
        String Userpassword = new String(TxtCUPass.getPassword());
        String Userconfirmpassword = new String(TxtCCPass.getPassword());
        
        if(Userpassword.isEmpty()||Userconfirmpassword.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please insert password!!!", "Warning!!",JOptionPane.WARNING_MESSAGE);
        return;
        } else if (!Userpassword.equals(Userconfirmpassword)) {
            JOptionPane.showMessageDialog(null, "Please insert the same confirm password as the password!!!", "Warning!!",JOptionPane.WARNING_MESSAGE);
            return;
            }

        User Create = new User(Username,Userid,Userpassword);
        
        if(Create.CreateUser())
            {
            JOptionPane.showMessageDialog(null, "User Created Successfully");
            this.setVisible(false);
            new UserPage().setVisible(true);
            }
        }
    }//GEN-LAST:event_BtnCreateUserActionPerformed

    private void TxtCUNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCUNKeyReleased
       String PATTERN ="^[a-zA-Z-]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(TxtCUN.getText());
        if(!match.matches())
        {
        LblValidName.setText("Naming Structure Incorrect !!");
        }
        else{
        LblValidName.setText("");
        }
    }//GEN-LAST:event_TxtCUNKeyReleased

    private void TxtCCPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCCPassKeyReleased
        String Cpass = new String(TxtCCPass.getPassword());
        String PATTERN ="^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,12}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(Cpass);
        if(!match.matches())
        {
          LblValidCPass.setText("Password Structure Incorrect !!");  
        }
        else
        {
          LblValidCPass.setText("");
        }
        
    }//GEN-LAST:event_TxtCCPassKeyReleased

    private void TxtCUPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCUPassKeyReleased
        String pass = new String(TxtCCPass.getPassword());
        String PATTERN ="^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,12}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(pass);
        if(!match.matches())
        {
          LblValidPass.setText("Password Structure Incorrect !!");  
        }
        else
        {
          LblValidPass.setText("");
        }
    }//GEN-LAST:event_TxtCUPassKeyReleased

    private void TxtCUPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCUPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCUPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnCreateUser;
    private javax.swing.JLabel LblCCPass;
    private javax.swing.JLabel LblCPass;
    private javax.swing.JLabel LblCUID;
    private javax.swing.JLabel LblCUName;
    private javax.swing.JLabel LblPT;
    private javax.swing.JLabel LblValidCPass;
    private javax.swing.JLabel LblValidName;
    private javax.swing.JLabel LblValidPass;
    private javax.swing.JPasswordField TxtCCPass;
    private javax.swing.JTextField TxtCUID;
    private javax.swing.JTextField TxtCUN;
    private javax.swing.JPasswordField TxtCUPass;
    // End of variables declaration//GEN-END:variables
}
