/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment;

import static java.awt.Color.blue;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class Floor2 extends javax.swing.JFrame {

 String Delimeter = "@#;";
    public Floor2() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }
            sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB = new javax.swing.JTable();
        panel5 = new java.awt.Panel();
        BtnF2R1 = new javax.swing.JButton();
        BtnF2R2 = new javax.swing.JButton();
        BtnF2R3 = new javax.swing.JButton();
        BtnF2R4 = new javax.swing.JButton();
        BtnF2R5 = new javax.swing.JButton();
        BtnF2R6 = new javax.swing.JButton();
        BtnF2R7 = new javax.swing.JButton();
        BtnF2R8 = new javax.swing.JButton();
        BtnF2R9 = new javax.swing.JButton();
        BtnF2R10 = new javax.swing.JButton();
        BtnReceipt = new javax.swing.JButton();
        BtnCreate = new javax.swing.JButton();
        BtnF1 = new javax.swing.JButton();
        BtnTable = new javax.swing.JButton();
        LblFloor2 = new javax.swing.JLabel();
        LblFloor3 = new javax.swing.JLabel();
        LblFloor4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MUser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MAbout = new javax.swing.JMenu();
        MbLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        JTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Customer IC", "Customer Contact Number", "Customer E-mail", "In Day", "Out Day", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JTBMouseMoved(evt);
            }
        });
        JTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTB);

        BtnF2R1.setText("R1");
        BtnF2R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R1ActionPerformed(evt);
            }
        });

        BtnF2R2.setText("R2");
        BtnF2R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R2ActionPerformed(evt);
            }
        });

        BtnF2R3.setText("R3");
        BtnF2R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R3ActionPerformed(evt);
            }
        });

        BtnF2R4.setText("R4");
        BtnF2R4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R4ActionPerformed(evt);
            }
        });

        BtnF2R5.setText("R5");
        BtnF2R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R5ActionPerformed(evt);
            }
        });

        BtnF2R6.setText("R6");
        BtnF2R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R6ActionPerformed(evt);
            }
        });

        BtnF2R7.setText("R7");
        BtnF2R7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R7ActionPerformed(evt);
            }
        });

        BtnF2R8.setText("R8");
        BtnF2R8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R8ActionPerformed(evt);
            }
        });

        BtnF2R9.setText("R9");
        BtnF2R9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R9ActionPerformed(evt);
            }
        });

        BtnF2R10.setText("R10");
        BtnF2R10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2R10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnF2R1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(BtnF2R2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnF2R3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnF2R4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnF2R5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnF2R6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BtnF2R7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnF2R8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BtnF2R9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnF2R10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnF2R1)
                    .addComponent(BtnF2R3)
                    .addComponent(BtnF2R4)
                    .addComponent(BtnF2R5)
                    .addComponent(BtnF2R6)
                    .addComponent(BtnF2R7)
                    .addComponent(BtnF2R8)
                    .addComponent(BtnF2R9)
                    .addComponent(BtnF2R10)
                    .addComponent(BtnF2R2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BtnReceipt.setText("Check Out");
        BtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReceiptActionPerformed(evt);
            }
        });

        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        BtnF1.setText("Floor 1");
        BtnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF1ActionPerformed(evt);
            }
        });

        BtnTable.setText("Full Booking");
        BtnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTableActionPerformed(evt);
            }
        });

        LblFloor2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblFloor2.setText("Floor 2");

        LblFloor3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        LblFloor4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblFloor4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kriso\\Downloads\\Webp.net-resizeimage (2).png")); // NOI18N

        MUser.setText("Manager");

        jMenuItem1.setText("User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MUser.add(jMenuItem1);

        jMenuBar1.add(MUser);

        MAbout.setText("Exit");

        MbLogout.setText("Logout");
        MbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbLogoutActionPerformed(evt);
            }
        });
        MAbout.add(MbLogout);

        jMenuBar1.add(MAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(506, 506, 506)
                                .addComponent(LblFloor3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblFloor4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblFloor2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(BtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(BtnF1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblFloor3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblFloor2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LblFloor4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnReceipt)
                    .addComponent(BtnTable)
                    .addComponent(BtnF1)
                    .addComponent(BtnCreate))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Floor 2 View Booking");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBMouseClicked
        int i = JTB.getSelectedRow();
        TableModel model = JTB.getModel();
        String CustomerName =  model.getValueAt(i,0).toString();
        String CustomerIC = model.getValueAt(i,1).toString();
        String CustomerContactNumber = model.getValueAt(i,2).toString();
        String CustomerEmail = model.getValueAt(i,3).toString();
        String InDay = model.getValueAt(i,4).toString();
        String OutDay = model.getValueAt(i,5).toString();
        String Room = model.getValueAt(i,6).toString();

        this.setVisible(false);
        F2Edit Edit = new F2Edit();
        Edit.setVisible(true);
        Edit.pack();
        Edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        Date Indate = null;
        try {
            Indate = new SimpleDateFormat("dd-MM-yyyy").parse(InDay);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(Floor2.class.getName()).log(Level.SEVERE, null, ex);
        }
        Date Outdate = null;
        try {
            Outdate = new SimpleDateFormat("dd-MM-yyyy").parse(OutDay);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(Floor2.class.getName()).log(Level.SEVERE, null, ex);
        }

        Edit.TxtECN.setText(CustomerName);
        Edit.TxtECIC.setText(CustomerIC);
        Edit.TxtECCN.setText(CustomerContactNumber);
        Edit.TxtEEM.setText(CustomerEmail);
        Edit.EDPID.setDate(Indate);
        Edit.EDPOD.setDate(Outdate);
        Edit.TxtERoom.setText(Room);

    }//GEN-LAST:event_JTBMouseClicked

    private void BtnF2R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R1")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R1ActionPerformed

    private void BtnF2R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R2ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R2")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R2ActionPerformed

    private void BtnF2R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R3")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R3ActionPerformed

    private void BtnF2R4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R4ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R4")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R4ActionPerformed

    private void BtnF2R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R5ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R5")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R5ActionPerformed

    private void BtnF2R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R6ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R6")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R6ActionPerformed

    private void BtnF2R7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R7ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R7")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R7ActionPerformed

    private void BtnF2R8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R8ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R8")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R8ActionPerformed

    private void BtnF2R9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R9ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R9")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R9ActionPerformed

    private void BtnF2R10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2R10ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R10")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnF2R10ActionPerformed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        this.setVisible(false);
        new F2Booking().setVisible(true);
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReceiptActionPerformed
        this.setVisible(false);
        new F2Payment().setVisible(true);
    }//GEN-LAST:event_BtnReceiptActionPerformed

    private void BtnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTableActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F2Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }
            sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnTableActionPerformed

    private void BtnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF1ActionPerformed
     this.setVisible(false);
     new Floor1().setVisible(true);
    }//GEN-LAST:event_BtnF1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"This is for Manager only !! Are you Manager ?","Warning!!",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            new Xstaff().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Sorry Staff in not available","Login Successful",JOptionPane.INFORMATION_MESSAGE );
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbLogoutActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Would you like to Logout?","Logout System",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
            Login a = new Login ();
            a.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_MbLogoutActionPerformed

    private void JTBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBMouseMoved
        int row = JTB.rowAtPoint(evt.getPoint());
      if (row > -1)
      {
         JTB.clearSelection();
         JTB.setRowSelectionInterval(row, row);
      }
      else
      {
         JTB.setSelectionBackground(blue);
      }
   
    }//GEN-LAST:event_JTBMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Floor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Floor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Floor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Floor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Floor2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JButton BtnF1;
    private javax.swing.JButton BtnF2R1;
    private javax.swing.JButton BtnF2R10;
    private javax.swing.JButton BtnF2R2;
    private javax.swing.JButton BtnF2R3;
    private javax.swing.JButton BtnF2R4;
    private javax.swing.JButton BtnF2R5;
    private javax.swing.JButton BtnF2R6;
    private javax.swing.JButton BtnF2R7;
    private javax.swing.JButton BtnF2R8;
    private javax.swing.JButton BtnF2R9;
    private javax.swing.JButton BtnReceipt;
    private javax.swing.JButton BtnTable;
    private javax.swing.JTable JTB;
    private javax.swing.JLabel LblFloor2;
    private javax.swing.JLabel LblFloor3;
    private javax.swing.JLabel LblFloor4;
    private javax.swing.JMenu MAbout;
    private javax.swing.JMenu MUser;
    private javax.swing.JMenuItem MbLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel5;
    // End of variables declaration//GEN-END:variables
}
