/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment;

import static java.awt.Color.blue;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class Floor1 extends javax.swing.JFrame {
String Delimeter = "@#;";

    /**
     * Creates new form StaffPage
     */
    public Floor1() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }
            sc1.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        BtnCreate = new javax.swing.JButton();
        BtnReceipt = new javax.swing.JButton();
        BtnF2 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB = new javax.swing.JTable();
        panel2 = new java.awt.Panel();
        BtnR1 = new javax.swing.JButton();
        BtnR2 = new javax.swing.JButton();
        BtnR3 = new javax.swing.JButton();
        BtnR4 = new javax.swing.JButton();
        BtnR5 = new javax.swing.JButton();
        BtnR6 = new javax.swing.JButton();
        BtnR7 = new javax.swing.JButton();
        BtnR8 = new javax.swing.JButton();
        BtnR9 = new javax.swing.JButton();
        BtnR10 = new javax.swing.JButton();
        BtnTable = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MUser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MAbout = new javax.swing.JMenu();
        MbLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        BtnReceipt.setText("Check Out");
        BtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReceiptActionPerformed(evt);
            }
        });

        BtnF2.setText("Floor 2");
        BtnF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnF2ActionPerformed(evt);
            }
        });

        JTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Name", "Customer IC", "Customer Contact Number", "Customer E-mail", "In Day", "Out Day", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JTBMouseMoved(evt);
            }
        });
        JTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTB);
        if (JTB.getColumnModel().getColumnCount() > 0) {
            JTB.getColumnModel().getColumn(5).setResizable(false);
        }
        JTB.getAccessibleContext().setAccessibleName("Floor 1 View Booking");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        BtnR1.setText("R1");
        BtnR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR1ActionPerformed(evt);
            }
        });

        BtnR2.setText("R2");
        BtnR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR2ActionPerformed(evt);
            }
        });

        BtnR3.setText("R3");
        BtnR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR3ActionPerformed(evt);
            }
        });

        BtnR4.setText("R4");
        BtnR4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR4ActionPerformed(evt);
            }
        });

        BtnR5.setText("R5");
        BtnR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR5ActionPerformed(evt);
            }
        });

        BtnR6.setText("R6");
        BtnR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR6ActionPerformed(evt);
            }
        });

        BtnR7.setText("R7");
        BtnR7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR7ActionPerformed(evt);
            }
        });

        BtnR8.setText("R8");
        BtnR8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR8ActionPerformed(evt);
            }
        });

        BtnR9.setText("R9");
        BtnR9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR9ActionPerformed(evt);
            }
        });

        BtnR10.setText("R10");
        BtnR10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnR10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(BtnR1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnR2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnR3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(BtnR4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnR5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BtnR6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BtnR7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnR8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BtnR9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BtnR10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnR1)
                    .addComponent(BtnR3)
                    .addComponent(BtnR4)
                    .addComponent(BtnR5)
                    .addComponent(BtnR6)
                    .addComponent(BtnR7)
                    .addComponent(BtnR8)
                    .addComponent(BtnR9)
                    .addComponent(BtnR10)
                    .addComponent(BtnR2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BtnTable.setText("Full Booking");
        BtnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTableActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Floor 1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kriso\\Downloads\\Webp.net-resizeimage (2).png")); // NOI18N

        MUser.setText("Manager");

        jMenuItem1.setText("User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MUser.add(jMenuItem1);

        jMenuBar1.add(MUser);

        MAbout.setText("Exit");

        MbLogout.setText("Logout");
        MbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbLogoutActionPerformed(evt);
            }
        });
        MAbout.add(MbLogout);

        jMenuBar1.add(MAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(BtnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(BtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(BtnF2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(677, 677, 677))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(517, 517, 517))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreate)
                    .addComponent(BtnReceipt)
                    .addComponent(BtnTable)
                    .addComponent(BtnF2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Floor 1 View Booking");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"This is for Manager only !! Are you Manager ?","Warning!!",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){
        new Xstaff().setVisible(true);
        this.setVisible(false);
        }
        else{
        JOptionPane.showMessageDialog(null,"Sorry Staff in not available","Login Successful",JOptionPane.INFORMATION_MESSAGE );
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbLogoutActionPerformed
    int n = JOptionPane.showConfirmDialog(null,"Would you like to Logout?","Logout System",JOptionPane.YES_NO_OPTION);
    if(n==JOptionPane.YES_OPTION){
    JOptionPane.showMessageDialog(null,"Goobye","Goodbye",JOptionPane.INFORMATION_MESSAGE );
    new Login().setVisible(true);
    this.setVisible(false);
    }

    }//GEN-LAST:event_MbLogoutActionPerformed

    private void BtnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTableActionPerformed
    DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            }
            sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnTableActionPerformed

    private void BtnR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R1")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR1ActionPerformed

    private void BtnR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR2ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R2")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR2ActionPerformed

    private void BtnR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR3ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R3")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR3ActionPerformed

    private void BtnR4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR4ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R4")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR4ActionPerformed

    private void BtnR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR5ActionPerformed
 DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R5")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR5ActionPerformed

    private void BtnR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR6ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R6")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR6ActionPerformed

    private void BtnR7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR7ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R7")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        } 
    }//GEN-LAST:event_BtnR7ActionPerformed

    private void BtnR8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR8ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R8")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR8ActionPerformed

    private void BtnR9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR9ActionPerformed
 DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R9")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR9ActionPerformed

    private void BtnR10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnR10ActionPerformed
DefaultTableModel model = (DefaultTableModel)JTB.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("F1Booking.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains("R10")){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }
    }//GEN-LAST:event_BtnR10ActionPerformed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
    this.setVisible(false);
     new F1Booking().setVisible(true);
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReceiptActionPerformed
     this.setVisible(false);
     new F1Payment().setVisible(true);
    }//GEN-LAST:event_BtnReceiptActionPerformed

    private void JTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBMouseClicked
       int i = JTB.getSelectedRow();
      TableModel model = JTB.getModel();
      String CustomerName =  model.getValueAt(i,0).toString();
      String CustomerIC = model.getValueAt(i,1).toString();
      String CustomerContactNumber = model.getValueAt(i,2).toString();
      String CustomerEmail = model.getValueAt(i,3).toString();
      String InDay = model.getValueAt(i,4).toString();
      String OutDay = model.getValueAt(i,5).toString();
      String Room = model.getValueAt(i,6).toString();
      
      this.setVisible(false);
      F1Edit Edit = new F1Edit();
      Edit.setVisible(true);
      Edit.pack();
      Edit.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      
      Date Indate = null;
    try {
        Indate = new SimpleDateFormat("dd-MM-yyyy").parse(InDay);
    } catch (ParseException ex) {
        java.util.logging.Logger.getLogger(Floor1.class.getName()).log(Level.SEVERE, null, ex);
    }
    Date Outdate = null;
    try {
        Outdate = new SimpleDateFormat("dd-MM-yyyy").parse(OutDay);
    } catch (ParseException ex) {
        java.util.logging.Logger.getLogger(Floor1.class.getName()).log(Level.SEVERE, null, ex);
    }
    
      
      Edit.TxtECN.setText(CustomerName);
      Edit.TxtECIC.setText(CustomerIC);
      Edit.TxtECCN.setText(CustomerContactNumber);
      Edit.TxtEEM.setText(CustomerEmail);
      Edit.EDPID.setDate(Indate);
      Edit.EDPOD.setDate(Outdate);
      Edit.TxtERoom.setText(Room);
      
      
    }//GEN-LAST:event_JTBMouseClicked

    private void BtnF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnF2ActionPerformed
     this.setVisible(false);
     new Floor2().setVisible(true);
    }//GEN-LAST:event_BtnF2ActionPerformed

    private void JTBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBMouseMoved
      int row = JTB.rowAtPoint(evt.getPoint());
      if (row > -1)
      {
         JTB.clearSelection();
         JTB.setRowSelectionInterval(row, row);
      }
      else
      {
         JTB.setSelectionBackground(blue);
      }
   
    }//GEN-LAST:event_JTBMouseMoved


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Floor1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JButton BtnF2;
    private javax.swing.JButton BtnR1;
    private javax.swing.JButton BtnR10;
    private javax.swing.JButton BtnR2;
    private javax.swing.JButton BtnR3;
    private javax.swing.JButton BtnR4;
    private javax.swing.JButton BtnR5;
    private javax.swing.JButton BtnR6;
    private javax.swing.JButton BtnR7;
    private javax.swing.JButton BtnR8;
    private javax.swing.JButton BtnR9;
    private javax.swing.JButton BtnReceipt;
    private javax.swing.JButton BtnTable;
    private javax.swing.JTable JTB;
    private javax.swing.JMenu MAbout;
    private javax.swing.JMenu MUser;
    private javax.swing.JMenuItem MbLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
