/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment;

import static java.awt.Color.blue;
import java.io.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Kriso
 */
public class UserPage extends javax.swing.JFrame {
public String Delimeter = "@#;";

    /**
     * Creates new form UserPage
     */
    public UserPage() {
        initComponents();
        
         DefaultTableModel model = (DefaultTableModel)JTBUser.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("User.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            } sc1.close();
        } catch (FileNotFoundException ex){ 
           JOptionPane.showMessageDialog(null, "Error Occurred");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExit = new javax.swing.JButton();
        TxtSearchUser = new javax.swing.JTextField();
        Btnserach = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTBUser = new javax.swing.JTable();
        BtnExit1 = new javax.swing.JButton();
        BtnCreate = new javax.swing.JButton();
        BtnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LblFloor4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        Btnserach.setText("Serach");
        Btnserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnserachActionPerformed(evt);
            }
        });

        JTBUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User Name", "User ID", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTBUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JTBUserMouseMoved(evt);
            }
        });
        JTBUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTBUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTBUser);

        BtnExit1.setText("Delete");
        BtnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit1ActionPerformed(evt);
            }
        });

        BtnCreate.setText("Craete");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        BtnView.setText("View");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        LblFloor4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LblFloor4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kriso\\Downloads\\Webp.net-resizeimage (2).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(BtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(BtnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblFloor4)
                .addGap(18, 18, 18)
                .addComponent(TxtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Btnserach, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btnserach)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblFloor4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnExit)
                    .addComponent(BtnExit1)
                    .addComponent(BtnCreate)
                    .addComponent(BtnView))
                .addGap(33, 33, 33))
        );

        getAccessibleContext().setAccessibleName("User Page");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnserachActionPerformed
    DefaultTableModel model = (DefaultTableModel)JTBUser.getModel();
    String search = TxtSearchUser.getText();
        model.setRowCount(0);
        try{
            File Flist = new File("User.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(Line.contains(search)){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }   
            }sc1.close();
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");  
        }        
        
        TxtSearchUser.setText("");
               
          
    }//GEN-LAST:event_BtnserachActionPerformed

    private void BtnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit1ActionPerformed
  int n = JOptionPane.showConfirmDialog(null,"Are You sure that You will want to Delete this User ?","Delete User",JOptionPane.YES_NO_OPTION);
    if(n==JOptionPane.YES_OPTION){
            if(JTBUser.getSelectedRowCount()==1){
                String UserNameJTBUser = String.valueOf(JTBUser.getValueAt(JTBUser.getSelectedRow(),0));
                
                String tempFile = "Temp.txt";
                String currentLine;
                String data[];
                try
                {
                    FileWriter fw = new FileWriter(tempFile,true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter pw = new PrintWriter(bw);
                    
                    FileReader fr = new FileReader("User.txt");
                    BufferedReader br =new BufferedReader(fr);
                    
                    while((currentLine = br.readLine())!= null)
                    
                    {
                    data = currentLine.split("@#;");
                    if(!(data[0].equalsIgnoreCase(UserNameJTBUser)))
                    {
                        pw.println(currentLine);
                    }
                    }
                    pw.flush();
                    fr.close();
                    br.close();
                    fw.close();
                    pw.close();
                    bw.close();
   
                }
                catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(null, "Error Occurred");
                
            }   catch (IOException ex) {
                    java.util.logging.Logger.getLogger(Floor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                File oldFile = new File ("User.txt");
                File newFile = new File (tempFile);
            System.out.println(oldFile.exists());
                    if (oldFile.delete()) { 
                System.out.println("Deleted the file: " + oldFile.getName());
                } else {
                System.out.println("Failed to delete the file.");
                    }
                    
                   newFile.renameTo(new File("User.txt"));
            }
            JOptionPane.showMessageDialog(null, "User Deleted Suceesfully");
    }
    DefaultTableModel model = (DefaultTableModel)JTBUser.getModel();
            model.setRowCount(0);
        try{
            File Flist = new File("User.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            } sc1.close();
        } catch (FileNotFoundException ex){ 
           JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    
                                     
    }//GEN-LAST:event_BtnExit1ActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
    int n = JOptionPane.showConfirmDialog(null,"Would you like to Exit?","Exit User Page",JOptionPane.YES_NO_OPTION);
    if(n==JOptionPane.YES_OPTION){
    JOptionPane.showMessageDialog(null, "GoodBye Manager");    
    new Floor1 ().setVisible(true);
    this.setVisible(false);
    }
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        this.setVisible(false);
        new CreateUser().setVisible(true);
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
       DefaultTableModel model = (DefaultTableModel)JTBUser.getModel();
        model.setRowCount(0);
        try{
            File Flist = new File("User.txt");         
            Scanner sc1 = new Scanner(Flist);
            while(sc1.hasNextLine()){
                String Line = sc1.nextLine();
                if(!(Line.isEmpty())){
                    String[] wordsinLine = Line.split(Delimeter);
                    model.addRow(wordsinLine);
                }
            } sc1.close();
        } catch (FileNotFoundException ex){ 
           JOptionPane.showMessageDialog(null, "Error Occurred");
        }
    }//GEN-LAST:event_BtnViewActionPerformed

    private void JTBUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBUserMouseMoved
      int row = JTBUser.rowAtPoint(evt.getPoint());
      if (row > -1)
      {
         JTBUser.clearSelection();
         JTBUser.setRowSelectionInterval(row, row);
      }
      else
      {
         JTBUser.setSelectionBackground(blue);
      }
    }//GEN-LAST:event_JTBUserMouseMoved

    private void JTBUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBUserMouseClicked

    }//GEN-LAST:event_JTBUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnExit1;
    private javax.swing.JButton BtnView;
    private javax.swing.JButton Btnserach;
    private javax.swing.JTable JTBUser;
    private javax.swing.JLabel LblFloor4;
    private javax.swing.JTextField TxtSearchUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
